# Generated by Django 5.1.7 on 2025-03-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('key', models.TextField()),
                ('algorithm', models.CharField(choices=[('OTP', 'One-Time Pad'), ('3DES', 'Triple DES'), ('AES', 'AES Encryption')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
