# Generated by Django 5.1.7 on 2025-03-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedmessage',
            name='decrypted_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='encryptedmessage',
            name='plain_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
